defaults:
  ado_project: Docker
  development_branch: chatgpt

services:
  edge-controller:
    repository: troy-cichosz/edge-controller
    ado_repository: edge-controller
    ado_pipeline: edge-controller - CI

  edge-time:
    repository: troy-cichosz/edge-time
    ado_repository: edge-time
    ado_pipeline: edge-time - CI

  edge-gps:
    repository: troy-cichosz/edge-gps
    ado_repository: edge-gps
    ado_pipeline: edge-gps - CI

  edge-video:
    repository: troy-cichosz/edge-video
    ado_repository: edge-video
    ado_pipeline: edge-video - CI

  edge-audio:
    repository: troy-cichosz/edge-audio
    ado_repository: edge-audio
    ado_pipeline: edge-audio - CI
